# Generated by Django 5.1.7 on 2025-05-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('education', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='created_at',
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.CharField(choices=[('hygiene', 'Menstrual Hygiene'), ('myths', 'Period Myths'), ('nutrition', 'Nutrition & Health'), ('first_period', 'First Period Guide')], default='hygiene', max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='articles/'),
        ),
    ]
